### ISSUE TITLE
[Proposal] use class as a type in constructor

### ISSUE THREAD

**Issue by khg0712** [vedantroy/typecheck.macro#10]
Is this feature is hard to impement?
If validator can be used with class in constructor, it would be better.

example
```
class A {
  a: number;
  b: string;
  constructor(a: A) {
    const vaildate = createValidator<A>();
    console.log('isVaild'+vaildate(a));
    this.a = a.a;
    this.b = a.b;
  }
}

new A({a: 1, b:'2'})
```

Currently, It makes `BABEL_TRANSFORM_ERROR` 😢

**Comment by vedantroy** [comment]
It seems hard/impossible to validate classes.

For example:
In your scenario, would need to verify that the `constructor` assigns the parameters to `this.a` and `this.b` and we might need to verify that the class inherits another class or has a certain private property or something. It seems un-definable.

I recommend doing something like follows:

```typescript
class A implements IData {
// class-specific things (inheritance, methods, etc.)
}

interface IData {
    a: number;
    b: string;
}

const hasCorrectData = createValidator<IData>()
```
